<?php
namespace app\index\controller;
use think\Controller;
use think\Session;


class Permission extends Controller
{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(!Session::get('id')) {
            $this->error('访问出错...', url('index/index'));
        }
    }


}
